app:
  kafka:
    task:
      topic: task
      group: default
logbook:
  predicate:
    include:
      - path: /api/**
logging:
  level:
    org:
      zalando:
        logbook: TRACE
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate:
      ddl-auto: validate